export const LOGIN_USER_SAGA = "LOGIN_USER_SAGA";
export const REGISTER_USER_SAGA = "REGISTER_USER_SAGA";
export const CHECK_LOGIN_SAGA = "CHECK_LOGIN_SAGA";

export const GET_ALL_USER_SAGA = "GET_ALL_USER_SAGA";
export const UPDATE_USER_SAGA = "UPDATE_USER_SAGA";
export const DELETE_USER_SAGA = "DELETE_USER_SAGA";

export const SEARCH_USER_SAGA = "SEARCH_USER_SAGA";
