export const GET_BANNER_SAGA = "GET_BANNER_SAGA";
export const GET_LIST_POPULAR_FILM_SAGA = "GET_LIST_POPULAR_FILM_SAGA";
export const GET_LIST_NEW_FILM_SAGA = "GET_LIST_NEW_FILM_SAGA";

export const ADD_BANNER_SAGA = "ADD_BANNER_SAGA";
export const DELETE_BANNER_SAGA = "DELETE_BANNER_SAGA";

export const ADD_NEW_FILM_SAGA = "ADD_NEW_FILM_ACTION";
export const DELETE_NEW_FILM_SAGA = "DELETE_NEW_FILM_ACTION";
export const EDIT_NEW_FILM_SAGA = "EDIT_NEW_FILM_SAGA";

export const ADD_POPULAR_FILM_SAGA = "ADD_POPULAR_FILM_SAGA";
export const DELETE_POPULAR_FILM_SAGA = "DELETE_POPULAR_FILM_SAGA";
export const EDIT_POPULAR_FILM_SAGA = "EDIT_POPULAR_FILM_SAGA";

export const GET_DETAIL_FILM_SAGA = "GET_DETAIL_FILM_SAGA";

export const ADD_EPISODE_FILM_SAGA = "ADD_EPISODE_FILM_SAGA";
export const GET_EPISODE_FILM_DETAIL_SAGA = "GET_EPISODE_FILM_DETAIL_SAGA";

export const GET_ALL_FILM_SAGA = "GET_ALL_FILM_SAGA";
export const GET_RECOMMEND_FILM_SAGA = "GET_RECOMMEND_FILM_SAGA";
